stages:

  data_ingestion:
    cmd: python -m src.components.data_ingestion
    deps:
      - src/components/data_ingestion.py
      - src/entity/config_entity.py
      - src/entity/artifact_entity.py
    params:
      - params.yaml:
          - data_ingestion.test_size
          - data_ingestion.source
          - data_ingestion.postgres
          - data_ingestion.s3
    outs:
      - artifact/data_ingestion

  data_validation:
    cmd: python -m src.components.data_validation
    deps:
      - src/components/data_validation.py
      - artifact/data_ingestion
      - config/schema.yaml
    params:
      - params.yaml:
          - data_ingestion.source
    outs:
      - artifact/data_validation

  data_transformation:
    cmd: python -m src.components.data_transformation
    deps:
      - src/components/data_transformation.py
      - artifact/data_ingestion
      - artifact/data_validation
    params:
      - params.yaml:
          - data_transformation.vectorizer
          - data_transformation.tfidf
          - data_transformation.hand_crafted_features
    outs:
      - artifact/data_transformation/transformed/train.npy
      - artifact/data_transformation/transformed/test.npy
      - artifact/data_transformation/transformed_object/preprocessing.pkl

  model_trainer:
    cmd: python -m src.components.model_trainer
    deps:
      - src/components/model_trainer.py
      - artifact/data_transformation/transformed/train.npy
      - artifact/data_transformation/transformed/test.npy
    params:
      - params.yaml:
          - model_trainer.naive_bayes.alpha
          - model_trainer.naive_bayes.fit_prior
          - model_trainer.cross_validation.n_splits
          - model_trainer.cross_validation.shuffle
          - model_trainer.cross_validation.random_state
          - model_trainer.random_state
    outs:
      - artifact/model_trainer/trained_model/model.pkl

  model_evaluation:
    cmd: python src/components/model_evaluation.py
    deps:
      - src/components/model_evaluation.py
      - artifact/model_trainer/trained_model/model.pkl
      - artifact/data_transformation/transformed/test.npy
    params:
      - params.yaml:
          - model_evaluation.experiment_name
          - model_evaluation.model_name
    metrics:
      - reports/metrics.json:
          cache: false
    outs:
      - reports/experiment_info.json:
          cache: false

  model_pusher:
    cmd: python src/components/model_pusher.py
    deps:
      - src/components/model_pusher.py
      - reports/experiment_info.json
      - artifact/model_trainer/trained_model/model.pkl
    params:
      - params.yaml:
          - model_pusher.alias
          - model_evaluation.model_name