data_ingestion:
  test_size: 0.2
  source: "both"  # "postgres" | "s3" | "both"

  postgres:
    table: "emails"
    query: "SELECT * FROM emails"

  s3:
    bucket_name: "email-bucket-mlops"
    file_key: "spam_assassin.csv"

data_validation:
  schema_path: "config/schema.yaml"

data_transformation:
  vectorizer: "TF-IDF"

model_trainer:
  xgboost:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    eval_metric: "logloss"
    random_state: 42

  cross_validation:
    n_splits: 5
    shuffle: true
    random_state: 42

model_evaluation:
  experiment_name: "Spam-Detection-XGBoost-v1"
  model_name: "Deep-Shield-Spam-Detector"

model_pusher:
  alias: "staging"