data_ingestion:
  test_size: 0.2
  source: "both"  # "postgres" | "s3" | "both"

  postgres:
    table: "emails"
    query: "SELECT * FROM emails"

  s3:
    bucket_name: "email-bucket-mlops"
    file_key: "spam_assassin.csv"

data_validation:
  schema_path: "config/schema.yaml"

data_transformation:
  vectorizer: "TF-IDF"
  tfidf:
    max_features: 30000
    ngram_range: [1, 2]
    sublinear_tf: true
    analyzer: "word"
    stop_words: "english"
    min_df: 3
    max_df: 0.90
    strip_accents: "unicode"

  hand_crafted_features:
    - caps_ratio
    - exclamation_count
    - url_count
    - dollar_count
    - html_flag
    - word_count
    - avg_word_length
    - digit_ratio
    - unique_word_ratio

model_trainer:
  naive_bayes:
    alpha: 0.1        # GridSearchCV se best mila tha notebook mein
    fit_prior: true

  cross_validation:
    n_splits: 5
    shuffle: true
    random_state: 42

  random_state: 42

model_evaluation:
  experiment_name: "Spam-Detection-NaiveBayes-v1"
  model_name: "Deep-Shield-Spam-Detector"

model_pusher:
  alias: "staging"