apiVersion: apps/v1
kind: Deployment

metadata:
  name: deep-shield-mail
  labels:
    app: deep-shield-mail

spec:
  replicas: 2

  selector:
    matchLabels:
      app: deep-shield-mail

  template:
    metadata:
      labels:
        app: deep-shield-mail

    spec:
      containers:
        - name: deep-shield-mail

          image: 343980058839.dkr.ecr.us-east-1.amazonaws.com/deep-shield-mail:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "1"

          env:
            - name: DEEPSHIELD_TEST
              valueFrom:
                secretKeyRef:
                  name: deepshield-secret
                  key: DEEPSHIELD_TEST

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: deepshield-secret
                  key: GOOGLE_CLIENT_ID

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: deepshield-secret
                  key: GOOGLE_CLIENT_SECRET

            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: deepshield-secret
                  key: FLASK_SECRET_KEY

---
apiVersion: v1
kind: Service

metadata:
  name: deep-shield-mail-service

spec:
  type: LoadBalancer

  selector:
    app: deep-shield-mail

  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000